controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    karp_base_controller:
      type: diff_drive_controller/DiffDriveController

karp_base_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.13
    #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.170

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link

    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    # pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    # twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    # open_loop: true
    open_loop: false
    enable_odom_tf: true

    cmd_vel_timeout: 0.5

    # publish_limited_velocity: true

    # unstamped velocity uses /karp_base_controller/cmd_vel_unstamped
    use_stamped_vel: false

    # stamped velocity uses /karp_base_controller/cmd_vel_unstamped
    # use_stamped_vel: true

    velocity_rolling_window_size: 10

    # publish limited velocity
    publish_cmd: true

    # publish wheel data
    publish_wheel_data: true

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 5.0
    linear.x.min_velocity: -5.0
    linear.x.min_acceleration: -6.0
    linear.x.max_acceleration: 6.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 6.28
    angular.z.min_velocity: -6.28
    angular.z.max_acceleration: 25.0
    angular.z.min_acceleration: -25.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0